"""Built-in detector families commonly used in radiation work."""

from __future__ import annotations

import numpy as np

from .universal import (
    DeadTimeModel,
    DetectorDescriptor,
    DetectorFamily,
    DetectorOutput,
    Directionality,
    ParticleResponse,
    RadiationType,
    ResponseCurve,
)

GAMMA_ENERGIES = (30.0, 60.0, 122.0, 356.0, 662.0, 1173.0, 1332.0, 2615.0)
SPECTRUM_BINS = tuple(float(value) for value in np.linspace(0.0, 3000.0, 121))


def _curve(values: tuple[float, ...]) -> ResponseCurve:
    return ResponseCurve(GAMMA_ENERGIES, values)


def _gamma(values: tuple[float, ...]) -> tuple[ParticleResponse, ...]:
    return (ParticleResponse(RadiationType.GAMMA, _curve(values)),)


def popular_detector_catalog() -> dict[str, DetectorDescriptor]:
    gamma_survey = _gamma((0.80, 0.72, 0.55, 0.28, 0.16, 0.09, 0.08, 0.04))
    gamma_spectroscopy = _gamma((0.65, 0.58, 0.48, 0.30, 0.22, 0.14, 0.12, 0.07))
    neutron_curve = ResponseCurve(
        (0.000025, 0.001, 1.0, 100.0, 1000.0, 10000.0),
        (0.75, 0.70, 0.42, 0.20, 0.12, 0.06),
    )
    alpha_curve = ResponseCurve((1000.0, 3000.0, 5500.0, 8000.0), (0.15, 0.35, 0.42, 0.38))
    beta_curve = ResponseCurve((50.0, 200.0, 500.0, 1000.0, 2500.0), (0.05, 0.22, 0.38, 0.44, 0.46))

    return {
        "gm_tube": DetectorDescriptor(
            "gm_tube",
            "Geiger-Mueller survey meter",
            DetectorFamily.GEIGER_MULLER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            gamma_survey,
            8.0e-4,
            background_cps=0.25,
            dead_time_s=190e-6,
            dead_time_model=DeadTimeModel.NONPARALYZABLE,
            maximum_count_rate_cps=5_000.0,
        ),
        "ion_chamber": DetectorDescriptor(
            "ion_chamber",
            "Pressurized ionization chamber",
            DetectorFamily.ION_CHAMBER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNT_RATE, DetectorOutput.DOSE_RATE),
            _gamma((0.92, 0.95, 0.98, 1.0, 1.0, 1.0, 1.0, 0.98)),
            2.0e-3,
            background_cps=0.02,
            dead_time_model=DeadTimeModel.NONE,
            maximum_count_rate_cps=5.0e8,
            dose_conversion_usv_h_per_count_kev=2.2e-8,
        ),
        "nai_tl": DetectorDescriptor(
            "nai_tl",
            "NaI(Tl) scintillation spectrometer",
            DetectorFamily.SCINTILLATOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE, DetectorOutput.SPECTRUM),
            gamma_spectroscopy,
            2.0e-3,
            background_cps=1.2,
            dead_time_s=2.0e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.07,
            energy_bin_edges_kev=SPECTRUM_BINS,
        ),
        "csi_tl": DetectorDescriptor(
            "csi_tl",
            "CsI(Tl) scintillation detector",
            DetectorFamily.SCINTILLATOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.SPECTRUM),
            _gamma((0.82, 0.75, 0.62, 0.39, 0.27, 0.17, 0.15, 0.09)),
            1.5e-3,
            background_cps=1.0,
            dead_time_s=3.0e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.085,
            energy_bin_edges_kev=SPECTRUM_BINS,
        ),
        "plastic_scintillator": DetectorDescriptor(
            "plastic_scintillator",
            "Plastic scintillation portal detector",
            DetectorFamily.SCINTILLATOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            _gamma((0.20, 0.18, 0.16, 0.13, 0.10, 0.08, 0.07, 0.05)),
            5.0e-2,
            background_cps=25.0,
            dead_time_s=20e-9,
            maximum_count_rate_cps=2.0e7,
        ),
        "hpge": DetectorDescriptor(
            "hpge",
            "HPGe gamma spectrometer",
            DetectorFamily.SEMICONDUCTOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.SPECTRUM),
            _gamma((0.58, 0.52, 0.43, 0.27, 0.20, 0.13, 0.12, 0.07)),
            2.5e-3,
            background_cps=0.15,
            dead_time_s=5e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.003,
            energy_bin_edges_kev=SPECTRUM_BINS,
        ),
        "czt": DetectorDescriptor(
            "czt",
            "CZT room-temperature spectrometer",
            DetectorFamily.SEMICONDUCTOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.SPECTRUM),
            _gamma((0.74, 0.65, 0.50, 0.25, 0.14, 0.07, 0.06, 0.025)),
            4.0e-4,
            background_cps=0.2,
            dead_time_s=1e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.025,
            energy_bin_edges_kev=SPECTRUM_BINS,
        ),
        "cdte": DetectorDescriptor(
            "cdte",
            "CdTe compact spectrometer",
            DetectorFamily.SEMICONDUCTOR,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.SPECTRUM),
            _gamma((0.78, 0.68, 0.49, 0.22, 0.11, 0.05, 0.04, 0.015)),
            2.5e-4,
            background_cps=0.15,
            dead_time_s=1.5e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.035,
            energy_bin_edges_kev=SPECTRUM_BINS,
        ),
        "proportional_counter": DetectorDescriptor(
            "proportional_counter",
            "Gas proportional counter",
            DetectorFamily.PROPORTIONAL_COUNTER,
            Directionality.COSINE,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            (
                ParticleResponse(RadiationType.ALPHA, alpha_curve, maximum_range_m=0.05),
                ParticleResponse(RadiationType.BETA, beta_curve, maximum_range_m=1.0),
            ),
            1.5e-2,
            background_cps=0.08,
            dead_time_s=10e-6,
            field_of_view_half_angle_deg=90.0,
            off_axis_leakage_fraction=0.0,
        ),
        "pancake_probe": DetectorDescriptor(
            "pancake_probe",
            "Alpha/beta pancake contamination probe",
            DetectorFamily.SURFACE_CONTAMINATION,
            Directionality.COSINE,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            (
                ParticleResponse(RadiationType.ALPHA, alpha_curve, maximum_range_m=0.04),
                ParticleResponse(RadiationType.BETA, beta_curve, maximum_range_m=0.7),
                ParticleResponse(RadiationType.GAMMA, _curve((0.03,) * len(GAMMA_ENERGIES))),
            ),
            1.55e-3,
            background_cps=0.15,
            dead_time_s=100e-6,
            field_of_view_half_angle_deg=90.0,
            off_axis_leakage_fraction=0.0,
        ),
        "he3_neutron": DetectorDescriptor(
            "he3_neutron",
            "Moderated He-3 neutron counter",
            DetectorFamily.NEUTRON_COUNTER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            (ParticleResponse(RadiationType.NEUTRON, neutron_curve),),
            1.0e-2,
            background_cps=0.02,
            dead_time_s=5e-6,
        ),
        "li6_zns_neutron": DetectorDescriptor(
            "li6_zns_neutron",
            "Li-6/ZnS neutron scintillator",
            DetectorFamily.NEUTRON_COUNTER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE),
            (ParticleResponse(RadiationType.NEUTRON, neutron_curve),),
            8.0e-3,
            background_cps=0.03,
            dead_time_s=1e-6,
        ),
        "neutron_rem_meter": DetectorDescriptor(
            "neutron_rem_meter",
            "Neutron rem meter",
            DetectorFamily.NEUTRON_COUNTER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNT_RATE, DetectorOutput.DOSE_RATE),
            (ParticleResponse(RadiationType.NEUTRON, neutron_curve),),
            2.0e-2,
            background_cps=0.01,
            dose_conversion_usv_h_per_count_kev=4.0e-8,
        ),
        "electronic_dosimeter": DetectorDescriptor(
            "electronic_dosimeter",
            "Electronic personal dosimeter",
            DetectorFamily.PERSONAL_DOSIMETER,
            Directionality.OMNIDIRECTIONAL,
            (DetectorOutput.COUNT_RATE, DetectorOutput.DOSE_RATE),
            _gamma((0.62, 0.72, 0.86, 0.96, 1.0, 1.0, 1.0, 0.95)),
            2.0e-4,
            background_cps=0.02,
            maximum_count_rate_cps=1.0e7,
            dose_conversion_usv_h_per_count_kev=2.2e-8,
        ),
        "collimated_nai": DetectorDescriptor(
            "collimated_nai",
            "Lead-collimated NaI directional detector",
            DetectorFamily.SCINTILLATOR,
            Directionality.COLLIMATED,
            (DetectorOutput.COUNTS, DetectorOutput.COUNT_RATE, DetectorOutput.DIRECTION),
            gamma_spectroscopy,
            2.0e-3,
            background_cps=0.3,
            dead_time_s=2e-6,
            field_of_view_half_angle_deg=22.0,
            off_axis_leakage_fraction=0.008,
        ),
        "rotating_shield": DetectorDescriptor(
            "rotating_shield",
            "Rotating shield directional counter",
            DetectorFamily.SCINTILLATOR,
            Directionality.ROTATING_COLLIMATOR,
            (DetectorOutput.COUNTS, DetectorOutput.DIRECTION),
            gamma_survey,
            1.2e-3,
            background_cps=0.3,
            dead_time_s=3e-6,
            field_of_view_half_angle_deg=35.0,
            off_axis_leakage_fraction=0.03,
        ),
        "coded_aperture_czt": DetectorDescriptor(
            "coded_aperture_czt",
            "CZT coded-aperture gamma camera",
            DetectorFamily.GAMMA_IMAGER,
            Directionality.CODED_APERTURE,
            (
                DetectorOutput.COUNTS,
                DetectorOutput.SPECTRUM,
                DetectorOutput.DIRECTION,
                DetectorOutput.IMAGE,
            ),
            gamma_spectroscopy,
            1.6e-3,
            background_cps=0.5,
            dead_time_s=1e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.025,
            energy_bin_edges_kev=SPECTRUM_BINS,
            field_of_view_half_angle_deg=45.0,
            off_axis_leakage_fraction=0.015,
        ),
        "compton_camera": DetectorDescriptor(
            "compton_camera",
            "Compton gamma camera",
            DetectorFamily.GAMMA_IMAGER,
            Directionality.COMPTON,
            (
                DetectorOutput.COUNTS,
                DetectorOutput.SPECTRUM,
                DetectorOutput.DIRECTION,
                DetectorOutput.IMAGE,
            ),
            _gamma((0.01, 0.02, 0.04, 0.09, 0.13, 0.16, 0.17, 0.20)),
            8.0e-3,
            background_cps=0.8,
            dead_time_s=0.5e-6,
            energy_resolution_fwhm_fraction_at_662kev=0.04,
            energy_bin_edges_kev=SPECTRUM_BINS,
            field_of_view_half_angle_deg=70.0,
            off_axis_leakage_fraction=0.05,
        ),
    }
